# Generated by Django 4.2.10 on 2024-03-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('scheme_fund', models.CharField(max_length=100)),
                ('scheme_tenure', models.CharField(max_length=100)),
            ],
        ),
    ]
