# Generated by Django 4.2.10 on 2024-03-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_alter_appointmentschedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentschedule',
            name='qualifications',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
