# Generated by Django 4.2.10 on 2024-03-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_appointmentschedule_qualifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='users',
            name='Resume',
            field=models.FileField(default=1, upload_to='Resume/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='qualifications',
            field=models.CharField(choices=[('high_school', 'High School'), ('Degree', 'Degree'), ('masters', "Master's Degree"), ('phd', 'PhD')], max_length=20),
        ),
    ]
